import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { getBearer, supabaseServer } from "@/lib/supabase/server";
import { BLOOM_LEVELS, BLOOM_META, blankBloomCounts, type BloomLevel } from "@/lib/bloom";
import { groqText } from "@/lib/groq";

export const runtime = "nodejs";
export const maxDuration = 60;

type Ctx = { params: Promise<{ attemptId: string }> };

export async function GET(req: Request, ctx: Ctx) {
  try {
    const token = getBearer(req);
    if (!token) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const sb = supabaseServer(token);
    const { data: { user } } = await sb.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { attemptId } = await ctx.params;

    const { data: attempt } = await sb
      .from("quiz_attempts")
      .select("*, quiz:quizzes(name, code, owner_id), profile:profiles!quiz_attempts_student_id_fkey(full_name, school, grade)")
      .eq("id", attemptId)
      .maybeSingle();
    if (!attempt) return NextResponse.json({ error: "Attempt not found" }, { status: 404 });

    const { data: ans } = await sb.from("attempt_answers").select("is_correct, bloom_level").eq("attempt_id", attemptId);
    const correct = blankBloomCounts(); const totals = blankBloomCounts();
    (ans || []).forEach((x: { bloom_level: BloomLevel; is_correct: boolean | null }) => {
      totals[x.bloom_level] += 1; if (x.is_correct) correct[x.bloom_level] += 1;
    });

    // AI commentary
    let commentary = "";
    try {
      const lines = BLOOM_LEVELS.filter((l) => totals[l] > 0)
        .map((l) => `- ${BLOOM_META[l].label}: ${correct[l]}/${totals[l]}`).join("\n");
      commentary = await groqText(
        `You are a school report-card writer. Write a single-paragraph teacher comment (3-4 sentences) about a student's Bloom-level performance. Highlight a strength and an area to develop. Encouraging but honest.`,
        `Student: ${attempt.profile?.full_name || "Student"}
Score: ${attempt.score}/${attempt.total}
${lines}`
      );
    } catch { commentary = "Continue practising consistently to build deeper understanding."; }

    // Build PDF
    const doc = new jsPDF();
    doc.setFillColor(5, 150, 105);
    doc.rect(0, 0, 210, 22, "F");
    doc.setTextColor(255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("BloomIQ — Student Report Card", 14, 14);

    doc.setTextColor(20);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    let y = 32;
    doc.text(`Student: ${attempt.profile?.full_name || "—"}`, 14, y); y += 6;
    if (attempt.profile?.school) { doc.text(`School: ${attempt.profile.school}`, 14, y); y += 6; }
    if (attempt.profile?.grade)  { doc.text(`Grade:  ${attempt.profile.grade}`, 14, y); y += 6; }
    doc.text(`Quiz:   ${attempt.quiz?.name || "—"}  (code ${attempt.quiz?.code || "—"})`, 14, y); y += 6;
    doc.text(`Date:   ${attempt.submitted_at ? new Date(attempt.submitted_at).toLocaleString() : "—"}`, 14, y); y += 8;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(28);
    doc.setTextColor(5, 150, 105);
    const percent = attempt.total ? Math.round((attempt.score / attempt.total) * 100) : 0;
    doc.text(`${attempt.score}/${attempt.total}  (${percent}%)`, 14, y + 6);
    doc.setTextColor(20);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    y += 16;

    doc.setFont("helvetica", "bold");
    doc.text("Bloom's Taxonomy breakdown", 14, y); y += 4;
    autoTable(doc, {
      startY: y,
      head: [["Level", "Description", "Correct", "Score"]],
      body: BLOOM_LEVELS.map((l) => [
        BLOOM_META[l].label,
        BLOOM_META[l].description,
        `${correct[l]}/${totals[l]}`,
        totals[l] ? `${Math.round((correct[l] / totals[l]) * 100)}%` : "—",
      ]),
      headStyles: { fillColor: [241, 245, 249], textColor: 30, fontStyle: "bold" },
      bodyStyles: { fontSize: 10 },
      styles: { cellPadding: 2 },
      columnStyles: { 2: { halign: "center" }, 3: { halign: "center", fontStyle: "bold" } },
    });

    // @ts-expect-error jspdf-autotable adds lastAutoTable to the doc
    const after = (doc.lastAutoTable?.finalY || y) + 10;
    doc.setFont("helvetica", "bold");
    doc.text("Teacher comment", 14, after);
    doc.setFont("helvetica", "normal");
    const split = doc.splitTextToSize(commentary, 180);
    doc.text(split, 14, after + 6);

    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("Generated by BloomIQ", 14, 285);

    const bytes = doc.output("arraybuffer");
    return new NextResponse(bytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="bloomiq-report-${attemptId.slice(0, 8)}.pdf"`,
      },
    });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed" }, { status: 500 });
  }
}
