-- =============================================================================
-- 66_bloomiq_score_calibration.sql
-- -----------------------------------------------------------------------------
-- Foundation for the BloomIQ Score + Future You feature.
--
-- The killer first-run experience for an independent student is a 7-minute,
-- 12-question Bloom-tagged calibration that produces a single 3-digit
-- "BloomIQ Score" (range 300-900, credit-score-style) plus a "Future You"
-- prediction (predicted exam rank + 3 named target colleges + the parallel
-- "Best You" delta they'd hit if they fixed their top-3 Bloom-level gaps).
--
-- The score persists, lives top-right of every student page, and updates
-- every time the student does a quiz or drill. Free shows daily updates;
-- Premium shows real-time updates + the specific actions that move it.
--
-- Three tables:
--
--   1. calibrations          — one row per user, holds the latest
--                              calibration result. Drives first-run gating
--                              ("if no row → show calibration prompt").
--                              Re-doing a calibration UPSERTs.
--
--   2. calibration_responses — append-only log of per-question answers
--                              from each calibration session. Keyed by
--                              calibration_id. Used to recompute scores
--                              if we change the algorithm, and to power
--                              future analytics ("which questions
--                              discriminate strong vs weak students best").
--
--   3. bloomiq_scores        — append-only time-series of score values.
--                              Calibration writes the first row. Every
--                              quiz/drill completion writes a new row via
--                              /api/student/score/recompute. The score
--                              badge reads the most recent row (ORDER BY
--                              calculated_at DESC LIMIT 1). Score history
--                              powers the trend chart and the "↑ from
--                              yesterday" delta on the badge.
--
-- All three tables are RLS-scoped: users can read/write their own rows
-- only. Admin/platform ops can use service-role to bypass.
--
-- The Bloom breakdown is stored as JSONB { remember, understand, apply,
-- analyze, evaluate, create } each a 0..1 mastery fraction. Storing as
-- a single column instead of six avoids schema churn if Bloom labels
-- ever evolve.
--
-- IMPORTANT: This migration does NOT add columns to public.profiles.
-- The score lives in bloomiq_scores keyed by user_id, queried with a
-- LIMIT 1 — same access pattern Supabase uses for subscriptions. Keeping
-- profiles narrow avoids cross-feature coupling.
-- =============================================================================

-- 1. CALIBRATIONS — one row per user (latest result)
create table if not exists public.calibrations (
  user_id uuid primary key references auth.users(id) on delete cascade,
  exam_goal text,
  -- Score and breakdown at the moment of completion. The bloomiq_scores
  -- table holds the time-series; this row is just a snapshot of the
  -- initial calibration result for first-run UX (the Future You reveal).
  initial_score integer not null check (initial_score between 300 and 900),
  initial_percentile integer check (initial_percentile between 0 and 100),
  initial_predicted_rank integer,
  bloom_breakdown jsonb not null default '{}'::jsonb,
  -- best_you_score / rank are computed at calibration time and frozen for
  -- the reveal screen — recomputing them would change the user's "target"
  -- on every visit and undermine the daily-progress narrative.
  best_you_score integer check (best_you_score between 300 and 900),
  best_you_predicted_rank integer,
  -- Top 3 Bloom levels the student is weakest at. Drives the "fix these
  -- to reach Best You" copy. Stored as text[] (e.g. {'apply','analyze','create'}).
  weakest_bloom_levels text[] not null default '{}',
  total_seconds integer,
  completed_at timestamptz not null default now(),
  -- model + algo version so we can identify rows generated by older
  -- versions when we tune the algorithm. Bumped manually on releases.
  algo_version text not null default 'v1.0',
  groq_model text
);

comment on table public.calibrations is
  'Latest calibration result per user. Drives first-run gating and the Future You reveal. UPSERTed when a user re-calibrates.';

create index if not exists calibrations_completed_idx
  on public.calibrations (completed_at desc);

-- 2. CALIBRATION_RESPONSES — per-question answer log (append-only)
create table if not exists public.calibration_responses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  -- Multiple sessions per user are allowed (re-calibration); session_id
  -- groups the 12 responses from one sitting.
  session_id uuid not null,
  question_index integer not null check (question_index between 0 and 99),
  -- The question text + options at the moment of asking, so we can
  -- reconstruct the experience even after the question gen prompt changes.
  question_stem text not null,
  options jsonb not null,
  correct_index integer not null check (correct_index between 0 and 3),
  selected_index integer check (selected_index between 0 and 3),
  is_correct boolean,
  bloom_level text not null check (bloom_level in
    ('remember','understand','apply','analyze','evaluate','create')),
  topic text,
  benchmark_seconds integer,
  time_taken_seconds integer,
  answered_at timestamptz not null default now()
);

comment on table public.calibration_responses is
  'Per-question log from each calibration session. Append-only. Used to recompute scores if the algorithm changes and to power discrimination analytics.';

create index if not exists calibration_responses_user_session_idx
  on public.calibration_responses (user_id, session_id);

create index if not exists calibration_responses_bloom_idx
  on public.calibration_responses (bloom_level);

-- 3. BLOOMIQ_SCORES — time-series of computed scores
create table if not exists public.bloomiq_scores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  score integer not null check (score between 300 and 900),
  percentile integer check (percentile between 0 and 100),
  predicted_rank integer,
  -- Same JSONB shape as calibrations.bloom_breakdown — a 0..1 fraction
  -- per Bloom level. Computed fresh on every recompute call.
  bloom_breakdown jsonb not null default '{}'::jsonb,
  -- Why was this score computed? Lets us slice the time-series by
  -- trigger ('calibration', 'quiz', 'drill', 'manual', 'daily_decay').
  trigger_event text not null default 'manual'
    check (trigger_event in
      ('calibration','quiz','drill','manual','daily_decay','recompute')),
  -- Optional FK to the source event (a quiz_attempts row id, etc.) so
  -- analytics can ask "which quizzes most affected scores".
  source_id uuid,
  calculated_at timestamptz not null default now()
);

comment on table public.bloomiq_scores is
  'Append-only time-series of BloomIQ Score values per user. The score badge reads the most recent row. History powers the trend chart and the day-over-day delta.';

create index if not exists bloomiq_scores_user_time_idx
  on public.bloomiq_scores (user_id, calculated_at desc);

-- =============================================================================
-- ROW-LEVEL SECURITY
-- -----------------------------------------------------------------------------
-- Strict per-user isolation: a student can only ever see their own
-- calibration, responses, and score history. Service-role bypasses for
-- admin/server work.
-- =============================================================================

alter table public.calibrations          enable row level security;
alter table public.calibration_responses enable row level security;
alter table public.bloomiq_scores        enable row level security;

-- calibrations
drop policy if exists "calibrations own select" on public.calibrations;
create policy "calibrations own select" on public.calibrations
  for select using (user_id = auth.uid());

drop policy if exists "calibrations own upsert" on public.calibrations;
create policy "calibrations own upsert" on public.calibrations
  for insert with check (user_id = auth.uid());

drop policy if exists "calibrations own update" on public.calibrations;
create policy "calibrations own update" on public.calibrations
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- calibration_responses
drop policy if exists "calib_responses own select" on public.calibration_responses;
create policy "calib_responses own select" on public.calibration_responses
  for select using (user_id = auth.uid());

drop policy if exists "calib_responses own insert" on public.calibration_responses;
create policy "calib_responses own insert" on public.calibration_responses
  for insert with check (user_id = auth.uid());

-- bloomiq_scores
drop policy if exists "bloomiq_scores own select" on public.bloomiq_scores;
create policy "bloomiq_scores own select" on public.bloomiq_scores
  for select using (user_id = auth.uid());

drop policy if exists "bloomiq_scores own insert" on public.bloomiq_scores;
create policy "bloomiq_scores own insert" on public.bloomiq_scores
  for insert with check (user_id = auth.uid());

-- =============================================================================
-- Schema reload hint for PostgREST so the new tables are immediately
-- queryable via the supabase-js client without a manual restart.
-- =============================================================================
notify pgrst, 'reload schema';
